// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6x4TmnHJFYJvEMDxCn2pG0WLev-CDpig',
    appId: '1:211670657191:web:05fdde11dbc5d482e3d382',
    messagingSenderId: '211670657191',
    projectId: 'flaapp-58aed',
    authDomain: 'flaapp-58aed.firebaseapp.com',
    storageBucket: 'flaapp-58aed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ExgmDtuKNiFPqMQhwXX4h7_IIA9NBOI',
    appId: '1:211670657191:android:e93f5c84fe071f96e3d382',
    messagingSenderId: '211670657191',
    projectId: 'flaapp-58aed',
    storageBucket: 'flaapp-58aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLnPMv0SpmV3g7sY8c4deFJ0SDAIMWCE',
    appId: '1:211670657191:ios:064bdcf158379ed8e3d382',
    messagingSenderId: '211670657191',
    projectId: 'flaapp-58aed',
    storageBucket: 'flaapp-58aed.appspot.com',
    iosBundleId: 'com.example.flaapp',
  );
}
